### ISSUE TITLE
Pitch Detector Ideas

### ISSUE THREAD

**Issue by ssj71** [geraldmwangi/GuitarSynth-DPF#2]
Hi Gerald:
I've been watching your thread on LAD but whenever I try to post nobody gets my messages. I just had a thought that perhaps you could actually use a monophonic method iteratively while removing each identified frequency between iterations. So something like aubio -> notch filter -> aubio -> notch filter  etc. Go until the energy in the strongest frequency is below some threshold. You could either use a notch filter or mix a pure sine in 180 degrees out of phase, since your fft will give you some phase info.
Drawbacks, this will be 6x more signal processing since you are running aubio over and over, and it will add latency for the filtering, and possibly transient smear. Removing each identified frequency through an out of phase sine could be cleaner, but takes some more thinking.
It may not work well enough for real time while using aubio, but you can probably find several optimizations when you roll your own method. Anyhow, I just wanted to pitch that to you. 
I find your project really interesting. I wanted to do the same thing myself while in school, but haven't thought about it much since.

**Comment by geraldmwangi** [comment]
well the problem is that aubio won't give sensible results when you play with more one note. But your idea correct and used to extent in the literature. The problem is how to detect the most strongest frequency comb (the fundamental+higher partials), since 2 or more combs/notes might be equally strong. But if your interested you can join me on the project, i can give you some papers to read (which i haven't read myself).
